language: php

sudo: false

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak

cache:
    directories:
      - $HOME/.composer/cache/files
      - .phpunit

before_install:
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi

before_script:
    # Symfony 2.8
    #- if [[ $SYMFONY_DEPS_VERSION = 2.8 ]]; then sed -i 's/~2\.8|^3\.0/2.8.*@dev/g' composer.json; fi
    #- composer update --no-suggest

script: ./vendor/bin/simple-phpunit

matrix:
    include:
        - php: 7.1
